const bancoDePreguntas = [
    //pregunta1ok
    { pregunta: "Su vehículo se desvía hacia un lado cuando usted frena. Usted debería:", opciones: ["Cambiar los neumáticos de un lado hacia el otro y viceversa.", "Bombear el pedal al frenar.", "Usar su freno de mano.", "Consultar con su mecánico lo antes posible."], c: [3], tipo: "una" },
    //pregunta2ok
    { pregunta: "Su vehículo se desvía hacia un lado cuando usted frena. ¿Cuál es la falla más probable?", opciones: ["Un bajo nivel del líquido de frenos.", "Su freno de mano está todavía puesto.", "Frenos mal ajustados.", "Neumáticos con presión de aire inadecuada."], c: [2], tipo: "una" },
    //pregunta3ok
    { pregunta: "Mientras conduce usted siente un fuerte olor a gasolina. ¿Qué debería hacer usted?", opciones: ["No preocuparse, ya que sólo son los gases de escape.", "Continuar a una velocidad reducida.", "Continuar porque sabe que se detendrá algunos kilómetros más allá.", "Detenerse e investigar el problema."], c: [3], tipo: "una" },   
    //pregunta4ok
    { pregunta: "¿Cómo puede prevenir usted el riesgo de incendio de su vehículo?", opciones: ["Manteniendo los niveles de agua sobre el máximo.", "Evitando conducir con el estanque lleno de combustible.", "Usando gasolina sin plomo.", "Revisando su vehículo ante cualquier olor a gasolina extraño."], c: [3], tipo: "una" },
    //pregunta5ok
    { pregunta: "¿Por qué es importante usar zapatos apropiados cuando conduce?", opciones: ["Para tener un adecuado control de los pedales.", "Para evitar el desgaste acelerado de las gomas de los pedales.", "Para poder efectuar los cambios de marcha más rápidamente.", "Para poder caminar sin problemas en el caso que necesite solicitar ayuda."], c: [0], tipo: "una" },
    //pregunta6ok
    { pregunta: "En un automóvil, ¿cuál de los siguientes elementos reduce el riesgo de lesiones de cuello en una colisión?", opciones: ["Un asiento dotado de air-bag (bolsa de aire).", "Los frenos ABS.", "Una columna de dirección colapsable.", "Un asiento con apoya-cabeza ajustado en forma apropiada"], c: [3], tipo: "una" },
    //pregunta7ok
    { pregunta: '¿Qué significa esta luz de advertencia en el panel de instrumentos?<br><img src="https://raw.githubusercontent.com/xelitoxd7/cuestionario-clase-b/refs/heads/main/pregunta7.jpg" style="width: 100%; max-width: 600px; height: auto; display: block; margin: 20px auto; border: 2px solid #ccc; border-radius: 8px;">', opciones: ["Luces neblineras.", "Intermitentes de advertencia de peligro.", "Luces altas.", "Freno de mano puesto."], c: [1], tipo: "una" },
    //pregunta8ok
    { pregunta: "Es esencial que la presión de los neumáticos sea chequeada regularmente. ¿Cuándo se debe hacer esto?", opciones: ["Después de un viaje largo.", "Después de conducir a alta velocidad.", "Cuando los neumáticos están fríos.", "Cuando los neumáticos están calientes."], c: [2], tipo: "una" },
    //pregunta9ok
    { pregunta: "La presión de los neumáticos debe revisarse:", opciones: ["Cuando los neumáticos están fríos.", "Cuando los neumáticos están calientes.", "En cualquier momento, porque da igual que los neumáticos estén fríos o calientes."], c: [0], tipo: "una" },
    //pregunta10ok
    { pregunta: "¿Cuál de estos líquidos, en el caso de estar en un nivel bajo, podría causar un accidente?", opciones: ["El líquido de freno.", "El anticongelante.", "El agua de la batería.", "El líquido refrigerante."], c: [0], tipo: "una" },
    //pregunta11ok
    { pregunta: "Frente a una situación normal, ¿cuál es la forma más segura de frenar?", opciones: ["Frenando fuerte, poniendo la palanca de cambio en neutro y tirando el freno de mano justo antes de detenerse.", "Frenando suavemente, presionando el pedal de embrague y tirando el freno de mano justo antes de detenerse.", "Poniendo la palanca de cambio en neutro, frenando fuerte y luego soltando el freno justo antes de detenerse.", "Frenando suavemente, luego un poco más fuerte cuando comienza a detenerse y después aflojando de a poco el freno antes de detenerse."], c: [3], tipo: "una" },
    //pregunta12ok
    { pregunta: "¿Cuándo usaría usted las luces intermitentes de advertencia de peligro?", opciones: ["Cuando esté en pana obstruyendo el tránsito.", "Cuando se estacione en doble fila respecto a otro vehículo estacionado junto a la cuneta.", "Cuando estacione junto a una cuneta en la que hay línea amarilla pintada.", "Cuando sus señalizadores de viraje no estén funcionando."], c: [0], tipo: "una" },
    //pregunta13ok
    { pregunta: "Las luces de advertencia de peligro deberían ser usadas:", opciones: ["Cuando estaciona en doble fila respecto a otro vehículo estacionado junto a la cuneta.", "Para advertir a quienes vienen detrás de un peligro que hay más adelante.", "Para advertir a quienes vienen detrás suyo que usted pretende virar.", "Para advertir a los demás que usted tiene prisa."], c: [1], tipo: "una" },
    //pregunta14ok
    { pregunta: "¿Cuándo usaría usted las luces de advertencia de peligro de su vehículo?", opciones: ["Cuando esté en pana moviéndose lentamente.", "Cuando esté siendo remolcado.", "Cuando esté retrocediendo en una calle de poco tránsito.", "Cuando esté en pana y obstaculizando el tránsito."], c: [3], tipo: "una" },
    //pregunta15ok
    { pregunta: "Usted está probando la suspensión de su vehículo cuando nota que éste rebota u oscila al cargarlo en un extremo lateral frontal. ¿Qué significa esto?", opciones: ["Neumáticos gastados.", "Neumáticos poco inflados.", "Volante de dirección no centrado.", "Amortiguadores gastados."], c: [3], tipo: "una" },
    //pregunta16ok
    { pregunta: "¿Por qué los neumáticos deben mantenerse a la presión indicada por el fabricante?", opciones: ["Para que el vehículo se mantenga a la altura correcta sobre la vía.", "Para no desgastar el motor.", "Para ayudar a evitar que el automóvil se roncee.", "Para evitar que el automóvil se incline hacia un lado."], c: [2], tipo: "una" },
    //pregunta17ok
    { pregunta: "¿A qué se debe un alto consumo de combustible?", opciones: ["Fallas en el sistema de dirección.", "Aceleraciones en curvas.", "Frecuentes frenadas y aceleraciones.", "Conducción en marchas altas."], c: [2], tipo: "una" },
    //pregunta18ok
    { pregunta: "La profundidad de los surcos de los neumáticos de un automóvil no debería ser inferior a ...", opciones: ["5.0 mm", "4.0 mm", "1.6 mm", "1.0 mm"], c: [2], tipo: "una" },
    //pregunta19ok
    { pregunta: "Uno de sus neumáticos traseros se revienta mientras usted conduce. ¿Cuáles 2 cosas debe hacer usted?", opciones: ["Poner marcha atrás para detener el vehículo.", "Hacer una señal de detención con el brazo y disminuir la velocidad.", "Detenerse lentamente al costado de la vía.", "Detener el vehículo frenando lo más fuerte que pueda.", "Girar el volante hacia el mismo lado hacia el cual se desvía la cola del vehículo."], c: [2, 4], tipo: "varias" },
    //pregunta20ok
    { pregunta: "¿Cuáles 2 cosas debe usted hacer si se le revienta un neumático delantero?", opciones: ["Cambiarse de pista y frenar a fondo.", "Frenar suavemente o dejar que el vehículo siga hasta detenerse.", "Frenar rápida y firmemente.", "Sostener firmemente el volante manteniendo la trayectoria.", "Sostener el volante con una mano advirtiendo con la otra a los demás que usted se detendrá."], c: [1, 3], tipo: "varias" },
    //pregunta21ok
    { pregunta: "¿Qué es lo que usted nunca debería hacer en una bomba de bencina?", opciones: ["Circular por ella", "Fumar", "Comer", "Lavar los parabrisas"], c: [1], tipo: "una" },
    //pregunta22ok
    { pregunta: "Desenganchar el motor del vehículo...", opciones: ["permite un mejor control al conductor.", "hace más fácil las maniobras.", "aumenta el consumo de combustible.", "reduce el control del conductor."], c: [3], tipo: "una" },
    //pregunta23ok
    { pregunta: "¿Por qué no es bueno desenganchar el motor del vehículo al ir circulando?", opciones: ["Porque ello hace que el vehículo resbale.", "Porque el motor se detendrá.", "Porque no hay frenado del motor.", "Porque el motor funcionará más rápido."], c: [2], tipo: "una" },
    //pregunta24ok
    { pregunta: "¿Cuáles son las 2 principales razones por las cuales no debe desengancharse el motor al ir cuesta abajo?", opciones: ["Porque tendrá menor control del frenado y dirección.", "Porque el vehículo agarrará velocidad.", "Porque el consumo de combustible será mayor.", "Porque se gastan y deterioran más los neumáticos.", "Porque se daña el motor."], c: [0, 1], tipo: "varias" },
    //pregunta25ok
    { pregunta: "¿Por qué usted no debería conducir presionando el pedal de embrague durante más tiempo que el necesario?", opciones: ["Porque reduce su control sobre el vehículo.", "Porque aumenta el desgaste de la caja de cambios.", "Porque aumenta el consumo de combustible.", "Porque reduce el agarre de los neumáticos."], c: [0], tipo: "una" },
    //pregunta26ok
    { pregunta: "¿Para qué sirven los seguros de niños de los vehículos?", opciones: ["Aseguran las hebillas de los cinturones de seguridad.", "Impiden que las puertas puedan abrirse desde el interior.", "Bloquean las ventanas traseras manteniéndolas cerradas.", "Impiden que los asientos se reclinen."], c: [1], tipo: "una" },
    //pregunta27ok
    { pregunta: "Una baja presión de aire en los neumáticos delanteros ...", opciones: ["hace que el vehículo tienda a torcer hacia un lado.", "mejora el rendimiento del combustible.", "hace sentir la dirección más liviana.", "hace sentir la dirección más pesada."], c: [3], tipo: "una" },
    //pregunta28ok
    { pregunta: "En un pavimento mojado, ¿influye el estado de los neumáticos en la distancia de frenado de su vehículo?", opciones: ["No, la distancia de frenado depende sólo de la velocidad.", "No, porque una vez que se acciona el freno la distancia de frenado es siempre la misma para cada vehículo.", "Sí, a mayor desgaste de los neumáticos menor es dicha distancia.", "Sí, porque el mayor o menor desgaste de los neumáticos, entre otros factores, determinará que dicha distancia sea mayor o menor."], c: [3], tipo: "una" },
    //pregunta29ok
    { pregunta: "¿Cuál o cuáles de las siguientes afirmaciones es(son) verdadera(s)?", opciones: ["Cuando el motor no está siendo lubricado se enciende una luz en el panel de instrumentos del vehículo.", "Una batería mal cargada hace que el vehículo tenga dificultades para arrancar.", "Casi siempre, el motor se enfría con un líquido refrigerante que circula por canales en el bloque del motor.", "Una temperatura del motor demasiado alta puede deberse a que se haya roto la correa de la bomba de agua."], c: [0, 1, 2, 3], tipo: "varias" },
    //pregunta30ok
    { pregunta: "¿Cuáles 2 de las siguientes afirmaciones son verdaderas?", opciones: ["Los gases de escape no son peligrosos para la salud de las personas.", "Un sistema de escape de gases oxidado puede hacer que penetre monóxido de carbono al interior del vehículo.", "Los gases de escape contienen monóxido de carbono, que carece de olor y es incoloro.", "Los vapores de la gasolina son inocuos."], c: [1, 2], tipo: "varias" },
    //pregunta31ok
    { pregunta: "¿Cuáles 2 de las siguientes afirmaciones son verdaderas?", opciones: ["A mayor velocidad, mayor es el consumo del líquido de frenos.", "Los frenos antibloqueo tienen la ventaja de impedir que las ruedas queden bloqueadas al frenar fuertemente.", "El consumo del líquido de frenos depende de la cantidad e intensidad de las frenadas.", "El líquido de frenos no se consume y si disminuye es porque hay algún defecto.", "Lo mejor es que el pedal de freno se sienta elástico."], c: [1, 3], tipo: "varias" },
    //pregunta32ok
    { pregunta: "¿Cuál o cuáles de las siguientes afirmaciones es(son) verdadera(s)?", opciones: ["Una profundidad de 1 mm de los surcos de las bandas de rodamiento de los neumáticos siempre es suficiente para asegurar una buena fricción con el pavimento.", "Un desgaste notorio de la zona central de las bandas de rodamiento de los neumáticos indica que éstos se han usado con muy poco aire.", "Un desgaste irregular de los neumáticos puede deberse a problemas de alineamiento o de amortiguación.", "Independientemente de la ubicación de las ruedas de tracción, para una mejor estabilidad del vehículo los mejores neumáticos deben ir adelante."], c: [2], tipo: "varias" },
    //pregunta33ok
    { pregunta: "¿Cuál o cuáles de las siguientes afirmaciones es(son) verdadera(s)?", opciones: ["El cinturón de seguridad disminuye las posibilidades de sufrir lesiones en un accidente.", "Los air-bags (o bolsas de aire) reemplazan ventajosamente al cinturón de seguridad.", "Para quienes viajan en el asiento trasero de un automóvil el cinturón de seguridad no les presta utilidad.", "Usar cinturón de seguridad es más necesario cuando se conduce en carreteras."], c: [0], tipo: "varias" },
    //pregunta34ok
    { pregunta: "¿Cuál o cuáles de las siguientes afirmaciones es(son) verdadera(s)?", opciones: ["No es seguro que un adulto lleve a un niño pequeño incluyéndolo en su cinturón de seguridad.", "El cinturón de seguridad disminuye las posibilidades de resultar lesionado en un accidente.", "Para quienes viajan en el asiento trasero el cinturón de seguridad no brinda mayor seguridad.", "Un cinturón de seguridad bien tensado brinda mayor seguridad que uno menos tensado."], c: [0, 1, 3], tipo: "varias" },
    //pregunta35ok
    { pregunta: "¿Qué elementos de su vehículo debe usted mantener limpios?", opciones: ["Las luces.", "Los espejos.", "Los neumáticos.", "Los vidrios."], c: [0, 1, 3], tipo: "varias" },
    //pregunta36ok
    { pregunta: "Suponga que en una ocasión,<br>• su distancia de reacción es de 10 metros<br>• su distancia de frenado es de 8 metros<br>• su distancia de detención (distancia de reacción más distancia de frenado) es de 18 metros<br><br>¿Cuál sería su distancia de detención si sigue conduciendo en calzada de idénticas características y condiciones, pero aumenta al doble su velocidad?", opciones: ["46 metros", "52 metros", "64 metros", "78 metros"], c: [1], tipo: "una" },
    //pregunta37ok
    { pregunta: "¿Cuál de las siguientes afirmaciones es falsa cuando usted aumenta su velocidad de 30 km/h a 60 km/h?", opciones: ["Se duplica la energía cinética.", "Se cuadruplica la energía cinética.", "Se duplica la distancia de reacción.", "Se cuadruplica la distancia de frenado."], c: [0], tipo: "una" },
    //pregunta38ok
    { pregunta: 'El auto azul circula a 70 km/h y el rojo a 90 km/h. ¿Dónde es más probable que sus conductores estimen el punto en que se producirá el encuentro de ambos vehículos?<br><img src="https://raw.githubusercontent.com/xelitoxd7/cuestionario-clase-b/refs/heads/main/pregunta38.jpg" style="width: 100%; max-width: 600px; height: auto; display: block; margin: 20px auto; border: 2px solid #ccc; border-radius: 8px;">', opciones: ["El conductor del auto rojo estima que dicho punto será el 3.", "El conductor del auto rojo estima que dicho punto será el 2.", "El conductor del auto azul estima que dicho punto será el 1.", "El conductor del auto azul estima que dicho punto será el 3."], c: [0, 3], tipo: "varias" },
    //pregunta39ok
    { pregunta: "¿Qué distancia de detención tiene un tren que circula a alrededor de 100 km/h?", opciones: ["Aproximadamente 100 metros.", "Aproximadamente 200 metros.", "Entre 800 y 1000 metros.", "Más de 2000 metros."], c: [2], tipo: "una" },
    //pregunta40ok
    { pregunta: "¿Qué es lo más importante para evitar chocar al vehículo que va adelante?", opciones: ["Asegurarse de que sus frenos sean eficientes.", "Conducir a una velocidad constante.", "Mantener una adecuada distancia de separación entre vehículos.", "Tener neumáticos en muy buen estado."], c: [2], tipo: "una" },
    //pregunta41ok
    { pregunta: "Usted va circulando a 50 km/h a lo largo de un camino plano y de asfalto. Las condiciones climáticas son buenas. Sus neumáticos y frenos también están buenos. En estas circunstancias, detenerse le tomará aproximadamente", opciones: ["unos 50 metros", "unos 15 metros", "unos 10 metros", "unos 30 metros"], c: [3], tipo: "una" },
    //pregunta42ok
    { pregunta: "La distancia de detención total es igual a la suma de la distancia de reacción y la de frenado. Aproximadamente, ¿cuál es la mínima distancia de detención total en un asfalto seco, si usted viaja a 90 km/h?", opciones: ["Unos 50 metros", "Unos 70 metros", "Unos 30 metros", "Unos 120 metros"], c: [1], tipo: "una" },
    //pregunta43ok
    { pregunta: "Usted conduce un vehículo con frenos y neumáticos en buenas condiciones. La superficie de calzada está seca. ¿Cuál es la distancia aproximada de detención total (distancia de reacción más distancia de frenado) si usted va a 70 km/h?", opciones: ["Unos 15 metros", "Unos 80 metros", "Unos 45 metros", "Unos 25 metros"], c: [2], tipo: "una" },
    //pregunta44ok
    { pregunta: "Usted desea estacionar en bajada en una calle con pendiente pronunciada. ¿Qué debería hacer?", opciones: ["Estacionar detrás de otro auto.", "Estacionar con dos ruedas sobre la acera.", "Dejar el volante girado hacia la acera.", "Dejar puesto el freno de mano."], c: [2, 3], tipo: "varias" },
    //pregunta45ok
    { pregunta: "Usted está descendiendo una pendiente muy larga. ¿Qué debería hacer para ayudar a controlar la velocidad de su vehículo?", opciones: ["Tomar el manubrio firmemente.", "Seleccionar una marcha baja.", "Seleccionar neutro.", "Presionar el pedal de embrague."], c: [1], tipo: "una" },
    //pregunta46ok
    { pregunta: "Usted está virando hacia la derecha en un camino resbaladizo y las ruedas traseras de su vehículo resbalan hacia la izquierda. ¿Qué debería hacer usted?", opciones: ["Frenar firmemente y no girar el manubrio.", "Guiar carefully hacia la izquierda.", "Usar el embrague y frenar firmemente.", "Girar hacia la derecha."], c: [1], tipo: "una" },
    //pregunta47ok
    { pregunta: "Usted está próximo a descender por una pendiente muy pronunciada. ¿Qué debería hacer para controlar la velocidad de su vehículo?", opciones: ["Seleccionar un cambio bajo y usar los frenos cuidadosamente.", "Seleccionar un cambio alto y usar los frenos cuidadosamente.", "Seleccionar un cambio alto y usar los frenos firmemente.", "Seleccionar un cambio bajo y evitar usar los frenos."], c: [0], tipo: "una" },
    //pregunta48ok
    { pregunta: "La distancia de frenado es la que recorre un vehículo desde que se presiona el freno hasta que el vehículo se detiene. En condiciones normales, ¿cuál sería aproximadamente su distancia de frenado si usted circula a 90 km/h?", opciones: ["Unos 45 metros", "Unos 70 metros", "Unos 20 metros", "Unos 15 metros"], c: [0], tipo: "una" },
    //pregunta49ok
    { pregunta: "¿Qué debería hacer usted para corregir un coletazo de las ruedas traseras?", opciones: ["No girar el volante del vehículo para nada.", "Girar el volante hacia el lado opuesto al coletazo.", "Girar el volante hacia el lado que se desplaza la cola del vehículo.", "Aplicar su freno de mano."], c: [2], tipo: "una" },
    //pregunta50ok
    { pregunta: "La distancia de frenado es la distancia que recorre un vehículo desde que se presiona el freno hasta que el vehículo se detiene. De las siguientes variables, ¿cuáles influyen en la distancia de frenado?", opciones: ["La velocidad.", "El alumbrado público.", "El estado de los frenos y neumáticos.", "Las condiciones climáticas.", "La hora del día."], c: [0, 2, 3], tipo: "varias" },
    //pregunta51ok
    { pregunta: "Usted va a 70 km/hr. Aproximadamente, ¿qué distancia recorrerá su vehículo desde el momento en que usted se percata de un peligro que hay más adelante hasta que comienza a frenar?", opciones: ["Unos 5 metros.", "Unos 8 metros.", "Unos 20 metros.", "Unos 30 metros."], c: [2], tipo: "una" },
    //pregunta52ok
    { pregunta: "¿Cuál es el tiempo de reacción promedio de un conductor ante un imprevisto?", opciones: ["1 segundo", "0.1 minuto", "0.1 segundo", "2 segundos"], c: [0], tipo: "una" },
    //pregunta53ok
    { pregunta: "¿Cuál o cuáles de las siguientes afirmaciones es(son) verdadera(s)?", opciones: ["Quien sobrestima sus habilidades para conducir conduce con frecuencia demasiado rápido.", "Quien sobrestima sus habilidades para conducir crea situaciones de riesgo a menudo.", "Con frecuencia, los muchachos jóvenes sobrestiman sus habilidades, conducen a velocidades excesivas y se ven más involucrados en accidentes que otros.", "Muchos conductores jóvenes muestran deficiencias en su madurez personal."], c: [0, 1, 2, 3], tipo: "varias" },
    //pregunta54ok
    { pregunta: "¿Cuál o cuáles de las siguientes afirmaciones es(son) verdadera(s) en cuanto al desarrollo de la moral de un individuo?", opciones: ["Durante la infancia, antes de llegar a la edad escolar, las personas son egocéntricas y piensan sobre todo en ellas mismas.", "Los conocimientos y la experiencia hacen que las personas se vuelvan más comprensivas.", "Como la moral de las personas es algo innato, no se puede cambiar.", "El comportamiento que tiene una persona como conductor muestra cuánto ha avanzado en el desarrollo de su moral."], c: [0, 1, 3], tipo: "varias" },
    //pregunta55ok
    { pregunta: "¿Cuáles 2 de las siguientes cualidades de un individuo denotan que ha alcanzado un alto grado de madurez personal?", opciones: ["No sobrestima sus habilidades; tiene un buen conocimiento de sí mismo.", "Mantiene su vehículo en muy buen estado.", "Tiene buen conocimiento de las normas que regulan el tránsito.", "Cuenta con que otros pueden cometer errores y los acepta."], c: [0, 3], tipo: "varias" },
    //pregunta56ok
    { pregunta: "¿Cuál de las siguientes afirmaciones es correcta en cuanto a la capacidad de reacción de los conductores jóvenes inexpertos, comparados con conductores experimentados cuya edad fluctúa entre 35 y 50 años?", opciones: ["Ante situaciones complejas, los conductores jóvenes reaccionan más rápido.", "Los conductores jóvenes reaccionan siempre con mayor rapidez.", "No hay diferencia entre la capacidad de reacción de los conductores jóvenes inexpertos y la de los mayores.", "En situaciones reales, que requieren reacciones complejas, los conductores experimentados reaccionan en un tiempo más corto que los jóvenes inexpertos."], c: [3], tipo: "una" },
    //pregunta57ok
    { pregunta: "¿Cuál o cuáles característica(s) distingue(n) a un conductor seguro?", opciones: ["Conduce con prudencia y hace todo lo posible por evitar accidentes.", "Es considerado y amable con los demás conductores y con los peatones.", "Es respetuoso, no obstaculiza ni perturba al resto.", "Conduce con buen criterio."], c: [0, 1, 2, 3], tipo: "varias" },
    //pregunta58ok
    { pregunta: "¿Cuáles 2 de los siguientes rasgos son característicos de personas que ceden con facilidad a la presión del grupo?", opciones: ["Por lo general, son muy inseguras de sí mismas.", "Sienten temor a ser motivo de bromas y risas de los demás.", "Tienen mayor autonomía y voluntad para defender sus opiniones.", "Son capaces de soportar bromas o que lo tilden de 'cobardes' o 'mala persona'.", "Son muy seguras de sí mismas."], c: [0, 1], tipo: "varias" },
    //pregunta59ok
    { pregunta: "De los siguientes factores que se presentan en los accidentes de tránsito, ¿cuáles son los 2 más frecuentes en los accidentes que ocurren en carreteras viéndose involucrado un solo vehículo?", opciones: ["Que el conductor no posea licencia para conducir.", "Que el conductor esté muy cansado o bajo los efectos del alcohol.", "Que el conductor esté bajo los efectos de medicamentos.", "Que el conductor sobrestime sus capacidades y conduzca a exceso de velocidad."], c: [1, 3], tipo: "varias" },
    //pregunta60ok
    { pregunta: "De los siguientes factores, ¿cuál es el que con mayor frecuencia se presenta en los accidentes de tránsito?", opciones: ["Los errores de los conductores.", "Las condiciones climáticas.", "Las condiciones de calles y caminos.", "Las fallas mecánicas."], c: [0], tipo: "una" },
    //pregunta61ok
    { pregunta: "En cuanto al estrés al conducir, ¿cuál de las siguientes afirmaciones es falsa?", opciones: ["Un grado demasiado alto de estrés disminuye su campo de atención.", "Un estrés moderado puede contribuir a mejorar su rendimiento.", "Un conductor muy estresado puede tener reacciones de pánico.", "El estrés no influye en absoluto en los actos de un conductor."], c: [3], tipo: "una" },
    //pregunta62ok
    { pregunta: "¿Qué puede esperarse de un conductor impulsivo?", opciones: ["Que reaccione adecuadamente ante cualquier imprevisto.", "Que actúe sin pensar en las consecuencias.", "Que conduzca con excesiva precaución.", "Que efectúe maniobras sorpresivas que sorprendan a los demás."], c: [1, 3], tipo: "varias" },
    //pregunta63ok
    { pregunta: "¿Cuál es el mejor consejo para una conducción segura?", opciones: ["Mantener el vehículo en muy buenas condiciones.", "Respetar los límites de velocidad.", "Evitar conducir durante la noche.", "Contar siempre con tiempo de sobra al conducir."], c: [3], tipo: "una" },
    //pregunta64ok
    { pregunta: "¿De cuáles 2 maneras puede usted contribuir con mayor eficacia a la seguridad de tránsito?", opciones: ["Contando siempre con tiempo de sobra para conducir.", "Manteniendo su vehículo en condiciones óptimas.", "Evitando conducir durante la noche.", "Conduciendo a la defensiva."], c: [0, 3], tipo: "varias" },
    //pregunta65ok
    { pregunta: "¿Cuál o cuáles de las siguientes afirmaciones es(son) verdadera(s)?", opciones: ["La capacidad de reacción de una persona se ve afectada con pequeñas concentraciones de alcohol en su organismo.", "Una buena taza de café acelera el proceso mediante el cual el organismo se libera del alcohol.", "Con pequeñas concentraciones de alcohol en el organismo de un individuo, disminuyen ciertas inhibiciones y tiende a sobrestimar sus capacidades.", "La capacidad de interpretación y decisión de un conductor experimentado no se ven afectadas con sólo 2 tragos de licor fuerte."], c: [0, 2], tipo: "varias" },
    //pregunta66ok
    { pregunta: "En cuanto a la concentración de alcohol en la sangre de una persona que ingiere la misma cantidad en ocasiones diferentes, ¿cuál de las siguientes afirmaciones es falsa?", opciones: ["Aunque la persona beba la misma cantidad de alcohol cada ocasión, la concentración de éste en su sangre puede ser diferente.", "La concentración de alcohol depende de cuánto se come en cada ocasión.", "Entre otros factores, la concentración de alcohol también depende del tiempo que dura la ingestión cada vez.", "Si la cantidad de alcohol ingerida en cada ocasión es exactamente la misma, la concentración de alcohol en la sangre también será la misma."], c: [3], tipo: "una" },
    //pregunta67ok
    { pregunta: "¿Qué efecto(s) sobre la visión tiene el conducir a unos 100 km/h?", opciones: ["A la mayoría de los conductores se les cansa la vista después de conducir más o menos media hora.", "El campo visual se reduce, ya que a esa velocidad se tiende a fijar la mirada recta a lo lejos.", "Resulta más difícil percibir movimientos a los lados de la carretera.", "La visión se adapta automáticamente a la alta velocidad y, por lo tanto, el resto del tránsito se percibe igual que al ir a una velocidad baja."], c: [1, 2], tipo: "varias" },
    //pregunta68ok
    { pregunta: "¿Cuáles son los primeros síntomas de cansancio?", opciones: ["Se comienza a sentir calor y agresividad.", "Se comienza a sentir falta de interés y aparecen los bostezos.", "Se comienza a sentir dificultad para mantener la dirección.", "Se comienza a sentir que los párpados se cierran."], c: [1], tipo: "una" },
    //pregunta69ok
    { pregunta: "El modo como percibimos una situación depende, entre otros factores, de nuestras experiencias anteriores, intereses, expectativas y necesidades. En este contexto, ¿cuál de las siguientes afirmaciones es falsa?", opciones: ["Un conductor que siente apremio por falta de tiempo puede subestimar los riesgos de la alta velocidad.", "Los conductores ven principalmente aquéllo que les interesa en un momento y lo que esperan ver.", "Varios conductores que ven lo mismo perciben las situaciones de tránsito también del mismo modo.", "También a los conductores experimentados a veces les pasan inadvertidas informaciones importantes."], c: [2], tipo: "una" },
    //pregunta70ok
    { pregunta: "De las siguientes afirmaciones, ¿cuál o cuáles es(son) verdadera(s)?", opciones: ["El factor humano es el principal causante de que surjan situaciones de riesgo en el tránsito.", "La falta de atención a las condiciones del tránsito es una de las principales causa de accidentes.", "Un conductor que va con mucha prisa tiende a subestimar los riesgos.", "Discutir con alguien o estar pendiente de la música de la radio, aumenta las posibilidades de pasar por alto circunstancias importantes en el tránsito."], c: [0, 1, 2, 3], tipo: "varias" },
    //pregunta71ok
    { pregunta: "En relación con la técnica de observación de los conductores inexpertos, ¿cuál o cuáles de las siguientes afirmaciones es(son) verdadera(s)?", opciones: ["Los conductores inexpertos concentran su mirada en puntos fijos.", "Los conductores inexpertos aprovechan al máximo su visión periférica.", "Los conductores inexpertos observan el entorno que los rodea en forma más sistemática que los conductores experimentados.", "No hay mayores diferencias en cuanto a cómo observan el entorno los conductores inexpertos y los con gran experiencia."], c: [0], tipo: "varias" },
    //pregunta72ok
    { pregunta: "¿Cuál o cuáles de las siguientes afirmaciones es(son) verdadera(s)?", opciones: ["El tener una buena visión es imprescindible para poder captar las diversas situaciones que se presentan al conducir.", "Existe un alto riesgo de que los conductores cuyo campo visual no es lo suficientemente amplio, no alcancen a reaccionar a tiempo ante peligros provenientes de los lados.", "Si usted conduce durante un largo tiempo en condiciones difíciles, puede tener problemas para apreciar correctamente lo que ve y, por lo tanto, tomar decisiones equivocadas.", "Las personas jóvenes son más sensibles a la luz deslumbrante que los mayores."], c: [0, 1, 2], tipo: "varias" },
    //pregunta73ok
    { pregunta: "¿Cuándo es alto el riesgo de interpretar erróneamente la realidad al conducir?", opciones: ["Cuando va por un camino montañoso y con muchas sinuosidades, y la visibilidad es muy mala.", "Cuando usted está muy cansado, especialmente si conduce de noche.", "Cuando va por carretera y existe una densa niebla.", "Cuando con buenas condiciones de visibilidad usted conduce por una carretera con buenas demarcaciones viales."], c: [0, 1, 2], tipo: "varias" },
    //pregunta74ok
    { pregunta: "¿Qué debería hacer usted si está tomando un remedio para la tos y no está seguro si éste puede afectar su conducción?", opciones: ["No conducir tan pronto haya ingerido el remedio, sino que esperar un rato.", "Conducir siempre que se sienta bien.", "Preguntar a su doctor.", "Solicitar consejo a un amigo o pariente."], c: [2], tipo: "una" },
    //pregunta75ok
    { pregunta: "Usted está tomando unos remedios que probablemente afectarán su conducción. ¿Qué debería hacer?", opciones: ["Limitar su conducción sólo a viajes esenciales.", "Conducir solamente acompañado por alguien que posea una licencia de conducir.", "Conducir sólo distancias cortas.", "Solicitar consejo médico antes de conducir."], c: [3], tipo: "una" },
    //pregunta76ok
    { pregunta: "Su doctor le ha recetado un tratamiento. ¿Por qué usted debe consultarle si puede conducir o no?", opciones: ["Porque algunas medicinas pueden hacer que sus reacciones sean más lentas.", "Porque las drogas influyen en su conducción al hacer más rápidas sus reacciones.", "Porque en caso de accidente no estaría cubierto por el Seguro Obligatorio.", "Porque las medicinas que está tomando pueden afectar su visión."], c: [0, 3], tipo: "varias" },
    //pregunta77ok
    { pregunta: "Si usted ha ingerido alcohol, ¿cuál o cuáles son los efectos más probables?", opciones: ["Su capacidad de coordinación se reducirá.", "Su autoconfianza se incrementará.", "Presentará ceguera al color.", "Sus reacciones serán más rápidas.", "Su juicio empeorará.", "Su capacidad de concentración aumentará."], c: [0, 1, 4], tipo: "varias" },
    //pregunta78ok
    { pregunta: "¿Cómo afecta el consumo de alcohol a su conducción?", opciones: ["Acelera sus reacciones.", "Aumenta su lucidez.", "Mejora su coordinación.", "Reduce su concentración."], c: [3], tipo: "una" },
    //pregunta79ok
    { pregunta: "Si usted va conduciendo y comienza a sentir cansancio, es mejor que se detenga lo antes posible. ¿Qué debería hacer usted mientras no pueda detenerse?", opciones: ["Aumentar su velocidad para encontrar pronto un lugar donde detenerse.", "Golpear suave y repetidamente el manubrio.", "Asegurarse de que entre aire fresco a su vehículo.", "Modificar permanentemente la velocidad para mejorar la concentración."], c: [2], tipo: "una" },
    //pregunta80ok
    { pregunta: "¿Qué consejo daría usted a un conductor que ha ingerido bebidas alcohólicas en una fiesta?", opciones: ["Que se vuelva a casa en taxi.", "Que tome una taza de café cargado y luego conduzca a casa.", "Que se vuelva a casa conduciendo lenta y muy cuidadosamente.", "Que espere un rato antes de irse conduciendo a casa."], c: [0], tipo: "una" },
    //pregunta81ok
    { pregunta: "Un conductor hace algo que a usted le molesta. ¿Qué debería hacer usted?", opciones: ["Hacerle saber cómo se siente.", "Encender y apagar sus luces delanteras repetidamente.", "Tratar de no reaccionar.", "Tocar la bocina."], c: [2], tipo: "una" },
    //pregunta82ok
    { pregunta: "Usted está a punto de volver a casa conduciendo, pero no puede encontrar los anteojos que necesita usar para conducir. ¿Qué debería hacer usted?", opciones: ["Conducir a casa lentamente por calles tranquilas.", "Encontrar una forma de llegar a casa sin manejar.", "Pedir prestados los anteojos a un amigo para volver conduciendo a casa.", "Manejar hasta su casa de noche para que las luces lo ayuden."], c: [1], tipo: "una" },
    //pregunta83ok
    { pregunta: "Usted está a punto de conducir, pero se siente enfermo. Usted debería ...", opciones: ["tomar una medicina antes de conducir.", "acortar el viaje si puede.", "no manejar.", "prometerse a sí mismo que se va a acostar tan pronto haya llegado a casa."], c: [2], tipo: "una" },
    //pregunta84ok
    { pregunta: "En relación con el cansancio y la conducción, de las siguientes afirmaciones, ¿cuál es falsa?", opciones: ["El cansancio es una causa importante de los accidentes que se registran en carreteras.", "Un conductor cansado ve empeorada su capacidad de reacción.", "Si un conductor está cansado, lo mejor es que su acompañante le vaya hablando permanentemente.", "El desorientarse y plantearse preguntas tales como, ¿pasé ya la ciudad X o aún no?, es un síntoma de cansancio."], c: [2], tipo: "una" },
    //pregunta85ok
    { pregunta: "Usted comienza a sentir cansancio en un viaje. ¿Qué debería hacer?", opciones: ["Detenerse y comer una gran comida.", "Detenerse inmediatamente y respirar profundo.", "Terminar el viaje y después dormir.", "Detenerse y dormir una pequeña siesta o detenerse y tomar un poco de café."], c: [3], tipo: "una" },
    //pregunta86ok
    { pregunta: "¿Qué precauciones debe tomar un conductor cuando asiste a un evento social?", opciones: ["Beber bastante café después de ingerir bebidas alcohólicas.", "Evitar circular por calles de mucho tráfico después de beber alcohol.", "Evitar beber alcohol con el estómago vacío.", "Evitar consumir alcohol."], c: [3], tipo: "una" },
    //pregunta87ok
    { pregunta: "De los siguientes efectos, ¿cuál no es consecuencia del consumo de alcohol antes de conducir?", opciones: ["Falsa sensación de confianza.", "Mayor conciencia del peligro.", "Menor control del vehículo.", "Escaso juicio de la velocidad."], c: [1], tipo: "una" },
    //pregunta88ok
    { pregunta: "De las siguientes capacidades de un individuo, ¿cuál de ellas no se ve afectada por el consumo de alcohol?", opciones: ["La percepción de colores.", "El juicio acerca de la velocidad.", "Los tiempos de reacción.", "La coordinación."], c: [0], tipo: "una" },
    //pregunta89ok
    { pregunta: "El tiempo que transcurre desde que usted percibe un peligro hasta que actúa se denomina tiempo de reacción. En una emergencia, ¿qué factor influye en su tiempo de reacción?", opciones: ["Su estado de salud.", "El estado de la calzada.", "La velocidad de su vehículo.", "Las condiciones climáticas."], c: [0], tipo: "una" },
    //pregunta90ok
    { pregunta: "¿Cuándo es más probable que usted pierda concentración cuando conduce?", opciones: ["Cuando hace funcionar los limpiaparabrisas.", "Cuando mira a través del espejo retrovisor.", "Cuando va escuchando música a alto volumen.", "Cuando utiliza un teléfono celular.", "Cuando mira un mapa del camino."], c: [2, 3, 4], tipo: "varias" }
];